# Generated by Django 6.0 on 2026-01-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
