# Generated by Django 6.0 on 2026-01-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_tourist_address_alter_tourist_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='address',
        ),
        migrations.AddField(
            model_name='tourist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourist',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tourist',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tourist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
