# Generated by Django 6.0 on 2026-01-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_addon_hotel_rename_price_tour_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='persons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
